name: social_media_app
description: "this is baslik"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  flutter_webrtc: ^0.12.7 
  supabase_flutter: ^2.6.0
  web_socket_channel: ^2.4.0
  http: ^1.5.0
  udp: ^5.0.3
  google_fonts: ^6.3.0
  video_player: ^2.8.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
