// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiFNoZ9MpVJZmyB1TET3coJABS62M_QJI',
    appId: '1:26363923537:web:e5b0090e8a43f9e269fc70',
    messagingSenderId: '26363923537',
    projectId: 'socialmedia-52031',
    authDomain: 'socialmedia-52031.firebaseapp.com',
    storageBucket: 'socialmedia-52031.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7YZk_tGp5QJYYfpvg_MhpyV-ExOlB84A',
    appId: '1:26363923537:android:846540d214b7bf8969fc70',
    messagingSenderId: '26363923537',
    projectId: 'socialmedia-52031',
    storageBucket: 'socialmedia-52031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsOOfL2zDYpeTWEZZgbF8D8CptH888aRU',
    appId: '1:26363923537:ios:be5e88df4cd6e6eb69fc70',
    messagingSenderId: '26363923537',
    projectId: 'socialmedia-52031',
    storageBucket: 'socialmedia-52031.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsOOfL2zDYpeTWEZZgbF8D8CptH888aRU',
    appId: '1:26363923537:ios:be5e88df4cd6e6eb69fc70',
    messagingSenderId: '26363923537',
    projectId: 'socialmedia-52031',
    storageBucket: 'socialmedia-52031.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiFNoZ9MpVJZmyB1TET3coJABS62M_QJI',
    appId: '1:26363923537:web:7671bc46cad4b32969fc70',
    messagingSenderId: '26363923537',
    projectId: 'socialmedia-52031',
    authDomain: 'socialmedia-52031.firebaseapp.com',
    storageBucket: 'socialmedia-52031.firebasestorage.app',
  );
}
